//
// Created by romain on 25/09/2020.
//

#ifndef POKEMON_SIMULATOR_VOLATILESTATUS_H
#define POKEMON_SIMULATOR_VOLATILESTATUS_H

enum VolatileStatus {
    BOUND,
    NO_ESCAPE,
    CONFUSION,
    CURSE,
    EMBARGO,
    ENCORE,
    FLINCH,
    HEAL_BLOCK,
    IDENTIFIED,
    LEECH_SEED,
    NIGHTMARE,
    PERISH_SONG,
    TAUNT,
    TELEKINESIS,
    TORMENT,
};

#endif //POKEMON_SIMULATOR_VOLATILESTATUS_H
